### PR TITLE
Adding support for Java 7

### PR DESCRIPTION
**Pull request by robotfood**
Hey João, can you take a look?

I used OpenJDK7 and tweaked the setup.xml file for Glassfish to all people to use Java 7. If it is good, we can duplicate this and modify for Java 8.

### CODE REVIEW

**Comment by jfloff** [comment]
Hey @robotfood 

Sounds good to me! Could the new dockerfile be in the main branch instead? We could have the following structure: a folder per each tag, one Dockerfile per folder:
```
6\
     Dockerfile
7\
     Dockerfile
```

Would that be ok?

**Comment by robotfood** [comment]
Hi João, that sounds fine to me.

Do you want me to move my changes to master + create those two folders in
the master branch?

/Emmett

On Mon, Dec 4, 2017 at 7:53 AM, João Ferreira Loff <notifications@github.com

**Comment by jfloff** [comment]
Yeah, go ahead! After that I'll fix the docker hub autobuild ;)

**Comment by robotfood** [comment]
Can you take a look now?

/Emmett

**Comment by jfloff** [comment]
Hi!

All looks good, I just saw 2 things:
- There are duplicate files within the `7/` folder (namely the LICENSE and README)
- There is a `.DS_Store` file in the `6/` folder, you could remove that. Tip: usually I add these in a global `.gitignore` (some hints [here](https://stackoverflow.com/questions/7335420/global-git-ignore)) so I don't add them to each repo `.gitignore`

**Comment by robotfood** [comment]
Done! Sorry about the delay! Long work week.

On Tue, Dec 5, 2017 at 9:27 AM, João Ferreira Loff <notifications@github.com

**Comment by jfloff** [comment]
No problem! I've deleted the branch for Java 7, and I've updated the build on Docker Hub! Whenever you feel like it you can add the Java 8 version ;)

**Comment by robotfood** [comment]
Oh sure! I can definitely do a version for JDK 8. I might add some
comments/sections in the previous Dockerfiles to fetch the MySQL connector
library, do you use that in your projects?

/Emmett

On Sat, Dec 9, 2017 at 4:00 PM, João Ferreira Loff <notifications@github.com

**Comment by jfloff** [comment]
I haven't messed up with my project in a while, but I was planing to mess around with databases so that connector might be a good thing to have! 

Go right ahead! 

PS: Now I know to whom I'll ask glassfish questions eheh :)

**Comment by robotfood** [comment]
No problem, playing with Docker is pretty fun.

What do you use such an old Glassfish version for? I'm very curious about
other folks like me stuck on that AS.

/Emmett

**Comment by jfloff** [comment]
Good question :) 

[mRUBiS](https://www.hpi.uni-potsdam.de/giese/public/mdelab/mdelab-projects/case-studies/mrubis/) is a proposal to turn the [RUBiS benchmark](http://rubis.ow2.org/) into a microservice-based architecture. 

Problem is, according to their design all the services share the same database, which defeats the whole microservice-oriented design. My plan was to change mRUBiS to "split" the database among the different services. 

I've been sidetrack recently developing another benchmark, but soon I have to get back to this ... :(

**Pull request closed without merging**
